name: CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/@control-api
          scoupe: '@control-api'

      - run: cd packages/common-ddb
      - run: npm install
      - run: npm build
      - run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{secrets.WORK_FLOW_TOKEN}
